package cmd

import (
	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:   "flowlint",
	Short: "Validate and refine Mermaid flow diagrams",
	Long: `flowlint is a CLI tool for validating, linting, and refining
Mermaid flow diagrams generated by the /flow skill.

It ensures diagrams follow consistent styling, proper arrow usage,
and complete coverage of dependencies.

Commands:
  validate  - Check Mermaid syntax with mermaid-cli
  lint      - Check style guide compliance and auto-fix
  check     - Verify diagram matches dependencies.yaml
  refine    - Run full refinement pipeline`,
}

func Execute() error {
	return rootCmd.Execute()
}

func init() {
	rootCmd.AddCommand(validateCmd)
	rootCmd.AddCommand(lintCmd)
	rootCmd.AddCommand(checkCmd)
	rootCmd.AddCommand(refineCmd)
}
